[project]
name = "fydp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Arannamoy Mondal", email = "arannamoymondal13@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.6",
    "pandas>=3.0.6",
]

[project.scripts]
fydp = "fydp:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
